name: Deploy Federation
on:
  push:	
    branches:	
      - main

jobs:
  deploy:
    name: Deploy Federation
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master

    - name: install dependencies
      run: |
        pip install -r requirements.txt

    - name: json-schema check on entity configuration
      run: |
        echo TODO

    - name: create openid-federation jwt
      run: |
        PRIVATE_JWK=`echo ${{ secrets.PRIVATE_JWK }} | base64 -d` python3 bin/create_jwt.py > federation/.well-known/openid-federation

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-trust-anchor
        FOLDER: federation
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
